# Section 9: `Task.*` values are never available within a Service, since a
# Service is not associated with any Task.
specificationVersion: jobtemplate-2023-09
extensions:
- SERVICE
- EXPR
name: TestJob
jobServices:
- name: Store
  ports:
  - name: main
  script:
    actions:
      onRun:
        command: python
        args: ["-c", "print()", "{{ Task.File.Run }}"]
steps:
- name: Step1
  script:
    actions:
      onRun:
        command: python
        args: ["-c", "print()", ]
