# Section 9 item 5.1 (RFC 0009): no two Environments in an external Service's
# `serviceEnvironments` may have the same name.
specificationVersion: environment-2023-09
extensions:
- SERVICE
- EXPR
services:
- name: Cache
  serviceEnvironments:
  - name: Conda
    variables:
      A: "1"
  - name: Conda
    variables:
      B: "1"
  ports:
  - name: main
  script:
    actions:
      onRun:
        command: python
        args: ["-c", "print()"]
